title: Re_Document
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Game Client Programmer

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://redocuspace.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Navigation
navigation:
    - title : About
      url : about
    - title : Portfolio
      url : portfolio
    - title : Hobby
      url : hobby
    - title : Contact
      url : contact
# About

# Post
post_layout_list:
    - title : Default
      url : one
    - title : two
      url : two
    - title : three
      url : three
    - title : four
      url : four
    - title : five
      url : five


# Study
studylist:
    - title : lauguage
      url : /study_language
      img : /assets/images/pic01.jpg
      description : 프로그래밍 언어
    - title : algorithm
      url : /study_algorithm
      img : /assets/images/pic01.jpg
      description : 자료구조 및 알고리즘
    - title : booklist
      url : /study_booklist
      img : /assets/images/pic01.jpg
      description : 기획 및 기타
    - title : study_license
      url : /study_license
      img : /assets/images/pic01.jpg
      description : 자격증 공부
    - title : gamelist
      url : /study_gamelist
      img : /assets/images/pic01.jpg
      description : 모작게임

# Project
projectlist:
    - title : single
      url : /project_single
      img : /assets/images/pic01.jpg
      description : 싱글 프로젝트


# Hobby
hobbylist:
    - title : novel
      url : /hobby_novel
      img : /assets/images/pic01.jpg
      description : Novel

# Contact


# imitation GameList
imitationlist:
    - title : tetris
      url : Hello World
      img : /assets/images/pic01.jpg
      description : Hello World
    
# Study_language List Manager

python_01_01:
    - title : 혼자 공부하는 파이썬
    - number : python_01_01
    - path : /post_study_language/
    - lecture:
      - number : python_01_01_01
      - name : 파이썬의 개요