title: Re_Document
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Game Client Programmer

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Navigation
navigation:
    - title : About
      url : one
    - title : Portfolio
      url : two
    - title : Project
      url : three
    - title : Study
      url : four
    - title : Post
      url : five
    - title : Contact
      url : six

# Study
studylist:
    - title : lauguage
      url : /study_language
      img : /assets/images/pic01.jpg
      description : Hello World