title: Re_Document
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Game Client Programmer

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://redocuspace.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

# 포트폴리오

# 프로젝트
project_management_list:
    - title : Unity 책 관리 프로젝트
      url : https://github.com/ReDocuSpace/Project_Book_Management
      img : /assets/images/avatar.jpg
      category : BookProject
      project_name : project_book
      index : "01"
    - title : Project Custom Game List
      url : /post/project/project_01_02
      img : /assets/images/avatar.jpg
      category : Project_Dictionary
      project_name : project_dictionary
      index : "02"

# 문서
docoument_management_list:
    - title : 문서 정리 사이트
      url : /document
      img : /assets/images/avatar.jpg
      category : document
      project_name : document
      index : "01"
    - title : 취미 블로그 사이트 [현재 준비중입니다.]
      url : /hobby
      img : /assets/images/avatar.jpg
      category : hobby
      project_name : hobby
      index : "02"


# 문서 학습
programming_basic_list:
    - title : 자료구조와 알고리즘
      img : /assets/document/image/Book_algorithm_01.jpg
      url : /post/programming_basic/algorithm_01_01_01
      category : algorithm01
    - title : 혼자 공부하는 파이썬
      img : /assets/document/image/Book01_language_python.jpg
      url : /post/programming_basic/python_01_01_01
      category : python01
    - title : 열혈 C 언어 
      img : /assets/document/image/Book02_language_cprogramming.jpg
      url : /post/programming_basic/cprogramming_01_01_01
      category : cprogramming01
    - title : 열혈 C++ 
      img : /assets/document/image/Book03_language_cprogramming.jpg
      url : /post/programming_basic/cprogramming_02_01_01
      category : cprogramming02
    - title : C# 교과서
      img : /assets/document/image/Book04_language_csharpprogramming.jpg
      url : /post/programming_basic/cprogramming_03_01_01
      category : cprogramming03
    - title : 손에 잡히는 프로세싱 
      img : /assets/document/image/Book10_language_Processing.jpg
      url : /post/programming_basic/processing_01_01_01
      category : processing01


programming_unity_list:
    - title : 게임 개발 기본
      img : /assets/document/image/Book_Unity_01.jpg
      url : /post/programming_intensify/unity_01_01_01
      category : unity01
    - title : 모바일 게임 개발
      img : /assets/document/image/Book_Unity_02.jpg
      url : /post/programming_intensify/unity_02_01_01
      category : unity02
    - title : 2d 게임 개발
      img : /assets/document/image/Book_Unity_03.jpg
      url : /post/programming_intensify/unity_03_01_01
      category : unity03
    - title : 게임 프로그래밍 바이블
      img : /assets/document/image/Book_Unity_04.jpg
      url : /post/programming_intensify/unity_04_01_01
      category : unity04
    - title : 3D 액션 게임
      img : /assets/document/image/Book_Unity_05.jpg
      url : /post/programming_intensify/unity_05_01_01
      category : unity05

etc_book_list:
    - title : Art Of Game Design
      img : /assets/document/image/Planner_Book_01.jpg
      url : /post/programming_etc_book/planner_01_01_01
    - title : 기획과 시나리오
      img : /assets/document/image/Planner_Book_02.jpg
      url : /post/programming_etc_book/planner_02_01_01
    - title : 게임 기획 멘토링
      img : /assets/document/image/Planner_Book_03.jpg
      url : /post/programming_etc_book/planner_03_01_01
    - title : 모바일 게임 기획
      img : /assets/document/image/Planner_Book_04.jpg
      url : /post/programming_etc_book/planner_04_01_01
    - title : 게임 기획 스쿨
      img : /assets/document/image/Planner_Book_05.jpg
      url : /post/programming_etc_book/planner_05_01_01

programming_conception_list:
    #- title : 세상을 만드는 글자, 코딩
    #  img : /assets/document/image/Book_programming_01.jpg
    #  url : /post/programming/programming_01_01_01
    #  category : programming01

# 정리 문서
create_study_list:
    - title : 제작중
      img : /assets/document/image/non_Image.png
      url : /post/create/create_01_01_01
      category : create_study

game_coby_list:
    - title : 모작게임
      img : /assets/document/image/Planner_Book_01.jpg
      url : /post/programming_game_copy/game_copy_main

# Hobby List
hobby_novel_list:
    - title : test
      img : /assets/document/image/Planner_Book_01.jpg
      url : /post/etc_book/planner_01_01_01