title: Re_Document
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Game Client Programmer

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://redocuspace.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Navigation
navigation:
    - title : About
      url : one
    - title : Study
      url : two
    - title : Project
      url : three
    - title : Portfolio
      url : four
    - title : Contact
      url : five
# About

# Post
post_layout_list:
    - title : Default
      url : one
    - title : two
      url : two
    - title : three
      url : three
    - title : four
      url : four
    - title : five
      url : five


# Study
studylist:
    - title : lauguage
      url : /study_language
      img : /assets/images/pic01.jpg
      description : Hello World
    - title : Hello World
      url : /study_language
      img : /assets/images/pic01.jpg
      description : Hello World

# Portfolio
portfoliolist:
    - title : portfolio
      url : /study_language
      img : /assets/images/pic01.jpg
      description : Hello World

# Project
projectlist:
    - title : project
      url : /study_language
      img : /assets/images/pic01.jpg
      description : Hello World

# Contact